docs/specification.md
packages/ark/source/crypto/networks/devnet/network.ts
packages/ark/source/crypto/networks/mainnet/network.ts
packages/ark/source/link.service.test.ts
packages/ark/source/networks/ark.devnet.ts
packages/ark/source/networks/ark.mainnet.ts
packages/ark/test/fixtures/client/configuration.json
packages/ark/test/fixtures/client/cryptoConfiguration.json
packages/markets/test/fixtures/coingecko/market.json
packages/profiles/source/host.repository.test.ts
packages/profiles/source/network.repository.test.ts
packages/profiles/source/transaction.dto.test.ts
packages/profiles/source/wallet.test.ts
packages/profiles/test/fixtures/client/configuration.json
packages/profiles/test/fixtures/client/cryptoConfiguration.json
packages/profiles/test/fixtures/coins/ark/mainnet/configuration.json
packages/profiles/test/fixtures/coins/ark/mainnet/cryptoConfiguration.json
packages/profiles/test/fixtures/network.json
packages/sdk/source/helpers.test.ts
packages/sdk/source/network.test.ts
packages/sdk/test/livenet/configuration-crypto.json
packages/sdk/test/livenet/configuration.json
packages/sdk/test/testnet/configuration-crypto.json
packages/sdk/test/testnet/configuration.json

```
explorer.ark.io  => live.arkscan.io
dexplorer.ark.io => test.arkscan.io
```

chore(ark): replace explorer urls

---

docs/profiles/wallets.md
packages/ark/source/networks/ark.devnet.ts
packages/ark/source/networks/ark.mainnet.ts
packages/profiles/source/wallet.repository.contract.ts
packages/profiles/source/wallet.repository.test.ts
packages/profiles/source/wallet.repository.ts
packages/profiles/test/fixtures/network.json

Adds a method to find wallets beloning to networks with a given nethash.

feat(profiles): implement `WalletRepository#findByCoinWithNethash`

---

packages/profiles/source/helpers/currency.test.ts
packages/profiles/source/helpers/currency.ts

Closes https://app.clickup.com/t/3ryzn21
round decimals properly

fix: round currency properly

---

packages/profiles/source/environment.test.ts
packages/profiles/source/serialiser.ts
packages/profiles/source/wallet.contract.ts
packages/profiles/source/wallet.enum.ts
packages/profiles/source/wallet.test.ts
packages/profiles/source/wallet.ts

Closes https://app.clickup.com/t/86dru3pq4

feat(profiles): add primary wallet setting

---

packages/mainsail/source/coin.provider.ts
packages/mainsail/source/crypto/networks/devnet/milestones.ts
packages/mainsail/source/crypto/networks/devnet/network.ts
packages/mainsail/source/networks/ark.devnet.ts
scripts/build-release.sh

Closes https://app.clickup.com/t/86drwpd0d

refactor: update mainsail network configuration

---

packages/mainsail/source/crypto/managers/config.ts
packages/mainsail/source/crypto/networks/mainnet/milestones.ts
packages/mainsail/source/transaction.service.ts

Closes https://app.clickup.com/t/86dt23bnh

refactor: update validator references in transaction service

---

packages/mainsail/source/fee.service.ts

Closes https://app.clickup.com/t/86dt1rbua

refactor: temporarily mock static fees

---

packages/mainsail/source/crypto/transactions/serializer.ts
packages/mainsail/source/transaction.service.ts

Closes https://app.clickup.com/t/86dt23xqj

fix: use correct tx version in transaction serializer

---

packages/mainsail/source/index.ts
packages/mainsail/source/manifest.ts
packages/mainsail/source/networks/mainsail.devnet.ts
packages/mainsail/source/networks/mainsail.mainnet.ts
packages/profiles/source/coin.service.ts

This will have additional network changes to let the Mainsail network exist alongside ARK for the time being

refactor: mainsail network configuration

---

packages/mainsail/source/transaction.service.ts

Removes the custom method for transfers since its compatible with current api
https://app.clickup.com/t/86dt3c54a

refactor: use transfer signature again

---

packages/mainsail/source/confirmed-transaction.dto.ts

https://app.clickup.com/t/86dt5q8hv

fix: create mainsail tx sender from public key api response

---

packages/mainsail/source/confirmed-transaction.dto.ts

Closes https://app.clickup.com/t/86dt6b3wg

fix: use correct path for transaction username

---

packages/mainsail/source/signed-transaction.dto.ts
packages/mainsail/source/transaction.service.ts
packages/sdk/source/signed-transaction.dto.ts

As a part of: https://app.clickup.com/t/86drv22ry

fix: username register/resign related bugs

---

packages/sdk/source/network.test.ts
packages/sdk/source/network.ts

https://app.clickup.com/t/86dt844zf

feat: add `Network#allowsLedger` method

---

packages/mainsail/source/wallet.dto.ts

https://app.clickup.com/t/86dt88y5c

fix: incorrect isDelegate condition

---

packages/mainsail/source/crypto/transactions/builders/index.ts
packages/mainsail/source/transaction.service.ts

https://app.clickup.com/t/86dt8fu38

refactor: use createFromData method on all transactions

---

packages/mainsail/source/networks/mainsail.devnet.ts
packages/mainsail/source/networks/shared.ts

https://app.clickup.com/t/86dt8x7v7

refactor: set mainsail fees to static

---

packages/ark/source/crypto/validation/index.ts

Closes https://app.clickup.com/t/86dtbb6db

fix: validate signature only if provided

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/label.yml
.github/workflows/validators.yml
pnpm-lock.yaml

Closes: https://app.clickup.com/t/86dtg8eg1

chore: upgrade Node and pnpm version for workflows

---

packages/mainsail/source/transaction.service.ts

Closes: https://app.clickup.com/t/86dtacbdn
Arkvault PR: https://github.com/ArdentHQ/arkvault/pull/512
Musig server PR: https://github.com/ArdentHQ/mainsail-musig-server/pull/24
This PR implements musig registration/resignation transactions. To test create a musig address and try to register/resign username.

refactor: implement username musig registration/resignation transactions

---

packages/mainsail/source/networks/mainsail.devnet.ts

Closes https://app.clickup.com/t/86dtt4g54

refactor: correct musig host for mainsail

---

packages/mainsail/source/multi-signature.service.ts

Closes https://app.clickup.com/t/86dtt6bn2

refactor: ensure multipayment tx amounts are bignumbers

---

packages/mainsail/source/client.service.ts

Closes: https://app.clickup.com/t/86dtxr3ab

chore: update transactions pool URL

---

packages/mainsail/source/networks/mainsail.devnet.ts

Closes https://app.clickup.com/t/86du8fxxk

refactor: adjust mainsail network config for evm

---

packages/ark/source/signed-transaction.dto.test.ts
packages/ark/source/signed-transaction.dto.ts
packages/profiles/source/signed-transaction.dto.ts
packages/sdk/source/signed-transaction.dto.contract.ts
packages/sdk/source/signed-transaction.dto.ts

Closes: https://app.clickup.com/t/86duyutgk
For testing: https://github.com/ArdentHQ/arkvault/pull/788

refactor: add votes/unvotes methods to retrieve voting info

---

packages/ark/source/confirmed-transaction.dto.ts
packages/ark/source/signed-transaction.dto.ts
packages/profiles/source/signed-transaction.dto.ts
packages/profiles/source/transaction.dto.ts
packages/sdk/source/confirmed-transaction.dto.contract.ts
packages/sdk/source/confirmed-transaction.dto.ts
packages/sdk/source/signed-transaction.dto.contract.ts
packages/sdk/source/signed-transaction.dto.ts

Closes: https://app.clickup.com/t/86dv24pw0
Companion PR: https://github.com/ArdentHQ/arkvault/pull/800

refactor: add `nonce` method for signed and confirmed transactions

---

packages/ark/source/multi-signature.service.ts

Closes: https://app.clickup.com/t/86dv453cr
For testing make a multipay musig transaction and sign it. 
Inspired from: https://github.com/ArdentHQ/platform-sdk/pull/95/files, thanks to @goga-m.

fix: ensure multipayment amounts are BigNumbers

---

.github/workflows/ci.yml
packages/mainsail/source/helpers/format-units.test.ts
packages/mainsail/source/helpers/format-units.ts
packages/mainsail/source/helpers/parse-units.test.ts
packages/mainsail/source/helpers/parse-units.ts

- Mainsail tests have been enabled in ci workflow.
- Imports in unit tests for mainsail have been fixed.

refactor: enable tests on mainsail

---

packages/profiles/source/wallet.ts

Closes: https://app.clickup.com/t/86dv8jk2f

fix: extract decimals from network config

---

packages/mainsail/source/transaction.service.ts

Updates consensus contract address

refactor: update consensus contract address

---

packages/mainsail/source/networks/shared.ts
scripts/manifest-updater.js

As a part of https://app.clickup.com/t/86dv1qb6b
Continuation of #128

chore: add feature flags for mainsail validator transactions

---

packages/mainsail/source/confirmed-transaction.dto.ts
packages/profiles/source/transaction.dto.ts
packages/sdk/source/confirmed-transaction.dto.contract.ts
packages/sdk/source/confirmed-transaction.dto.ts

Part of https://app.clickup.com/t/86dv94xf8

feat: expose transaction success state 

---

packages/mainsail/source/networks/shared.ts
packages/mainsail/source/transaction.service.ts

Part of https://app.clickup.com/t/86dvbkgwe

refactor: remove vendor field from transfers

---

packages/mainsail/source/confirmed-transaction.dto.ts
packages/mainsail/source/signed-transaction.dto.ts

As a part of: https://app.clickup.com/t/86dvbm0c9
This PR updates `votes` and `unvotes` methods for signed and confirmed transaction classes to extract voting data.

refactor: update voting methods for mainsail network

---

packages/mainsail/source/confirmed-transaction.dto.ts
packages/mainsail/source/signed-transaction.dto.ts
packages/mainsail/source/transaction.service.test.ts
packages/mainsail/source/transaction.service.votes.test.ts

Required for https://app.clickup.com/t/86dvbhaub

fix: correct fee unit in signed & confirmed tx dto

---

packages/mainsail/source/fee.service.ts
packages/mainsail/source/networks/mainsail.devnet.ts
packages/mainsail/source/networks/shared.ts

Closes: https://app.clickup.com/t/86dvcx6q5
This PR makes use of Mainsail API to return fee options.
Companion arkvault PR: https://github.com/ArdentHQ/arkvault/pull/880
In action:
[Screencast from 2024-12-20 19-33-08.webm](https://github.com/user-attachments/assets/52e25e21-b75d-4c8e-8625-b585856093e0)

refactor: return fee options for Mainsail

---

packages/mainsail/source/confirmed-transaction.dto.test.ts
packages/mainsail/source/confirmed-transaction.dto.ts
packages/mainsail/source/signed-transaction.dto.test.ts
packages/mainsail/source/signed-transaction.dto.ts
packages/mainsail/source/transaction.service.test.ts
packages/mainsail/source/transaction.service.votes.test.ts

Closes: https://app.clickup.com/t/86dvn5aak
Reverts https://github.com/ArdentHQ/platform-sdk/pull/143/files#diff-9ab5da5c6a4c8eab8958c82aa262e9ff88264a07754eac3fb06403ea6e9e970bL67
Now fees are shown correctly in arkvault:

fix: transaction fee formatting

---

packages/mainsail/source/client.service.ts

Closes https://app.clickup.com/t/86dvpfvpb

fix: allow transfer type in transaction query parameters

---

packages/mainsail/source/index.ts

Closes: https://app.clickup.com/t/86dvpuyym
This PR exposes `formatUnits` and `parseUnits` helpers for the `mainsail` package.

refactor: expose Mainsail formatting helpers

---

packages/mainsail/source/client.service.ts
packages/mainsail/source/confirmed-transaction.dto.ts
packages/mainsail/source/helpers/decode-function-data.ts
packages/mainsail/source/signed-transaction.dto.ts
packages/mainsail/source/transaction-type.service.ts
packages/mainsail/source/transaction.service.test.ts
packages/mainsail/source/transaction.service.ts

As a part of https://app.clickup.com/t/86dvxuq7t
This PR adds EVM calls for username registration and resignation.

feat: implement username registration/resignation calls

---

packages/profiles/source/contact-address.test.ts

- Tests for contact address have been refactored to support mainsail changes

refactor: contact address test

---

packages/mainsail/source/known-wallet.service.test.ts
packages/mainsail/source/networks/mainsail.devnet.ts

Related to https://app.clickup.com/t/86dvxbhey

refactor: update known wallet urls for mainsail devnet

---

packages/profiles/source/contact-address.repository.test.ts
packages/profiles/source/contact.repository.test.ts

- Tests for `contact` and `contact address` repositories in `mainsail` have been refactored to support this network

refactor: contact address repository test

---

packages/mainsail/package.json
packages/mainsail/source/ledger.service.ts
packages/mainsail/source/networks/mainsail.devnet.ts
pnpm-lock.yaml

Closes https://app.clickup.com/t/86dw33bdj

feat: setup eth ledger app for mainsail

---

packages/mainsail/source/ledger.service.ts

Closes https://app.clickup.com/t/86dw7apew

fix: allow scanning multiple ledger addresses 

---

packages/mainsail/source/link.service.test.ts
packages/mainsail/source/networks/mainsail.mainnet.ts

Fixes https://app.clickup.com/t/86dw0mq9m

refactor: remove deprecated ark endpoints from mainsail mainnet config

---

packages/profiles/source/transaction.aggregate.contract.ts
packages/profiles/source/transaction.aggregate.test.ts
packages/profiles/source/transaction.aggregate.ts

https://app.clickup.com/t/86dw6utee

fix: outgoing tab labelling

---

packages/mainsail/source/transaction.service.ts

Closes: https://app.clickup.com/t/86dwbjhf5
Load the arkvault and try send a multipayment tx with large numbers:

fix: multipayment amount

---

packages/profiles/source/wallet.service.contract.ts

As a part of: https://app.clickup.com/t/86dwfh8f6

chore: update `syncByProfile` signature
