packages/ark/source/client.service.test.ts
packages/ark/source/client.service.ts

FIxes the timestamp calculation for the api request.

fix(ark): subtract full epoch during timestamp calculation

---

packages/ark/source/client.service.ts

Adds a little safeguard to the timestamp calculation, so that negative values are never passed to the api, which would otherwise result in the node to return an error response (422).

refactor(ark): never build api requests with timestamps smaller than zero

---

packages/ark/source/client.service.test.ts
packages/ark/source/client.service.ts
packages/ark/source/ledger.service.test.ts
packages/profiles/source/notification.service.test.ts
packages/profiles/source/notification.transactions.service.test.ts
packages/profiles/source/transaction-index.test.ts
packages/profiles/source/transaction.aggregate.test.ts
packages/profiles/source/wallet.test.ts

https://app.clickup.com/t/2mez868
Refactors the legacy API check on a  response to the `/api/wallets/search [POST]` endpoint instead of the networks' name, as this endpoint is only present on legacy networks.

refactor(ark): use api response to decide if network is legacy

---

packages/ark/source/client.service.test.ts
packages/ark/source/client.service.ts
packages/ark/source/ledger.service.test.ts
packages/profiles/source/notification.service.test.ts
packages/profiles/source/notification.transactions.service.test.ts
packages/profiles/source/transaction-index.test.ts
packages/profiles/source/transaction.aggregate.test.ts
packages/profiles/source/wallet.test.ts

Follow up to https://github.com/ArdentHQ/platform-sdk/pull/11: use `api/wallets?limit=1&nonce=0 [GET]` as query instead of the previous POST request against the search endpoint.

fix(ark): adjust query used to determine if legacy and store status for each network

---

packages/profiles/source/notification.service.test.ts
packages/profiles/source/notification.transactions.service.test.ts
packages/profiles/source/transaction-index.test.ts
packages/profiles/source/transaction.aggregate.test.ts
packages/profiles/source/wallet.service.test.ts
packages/profiles/source/wallet.service.ts
packages/profiles/source/wallet.test.ts

https://app.clickup.com/t/30cpn1g
Instead of syncing all wallets, we can sync only those pertaining to available networks.
Goes hand in hand with https://github.com/ArdentHQ/arkvault/pull/195.

refactor(profiles): only sync wallets of available networks

---

packages/profiles/source/wallet.service.ts

Default and custom networks are stored slightly different on the profile, i.e. disabled default networks are excluded from `profile.availableNetworks()` while disabled custom networks are included, but have their `network.meta().enabled` flag set to false. This flag is not used by default networks.

refactor(profiles): check if networks are enabled

---

packages/profiles/source/environment.test.ts
packages/profiles/source/profile.enum.contract.ts
packages/profiles/source/profile.test.ts
packages/profiles/source/profile.validator.test.ts
packages/profiles/source/profile.validator.ts

Closes https://app.clickup.com/t/86dru3pn5
Allows the following fields to be included & persisted in profile settings:
* `sessions` Object
* `hasOnboarded` Boolean
* `lastVisitedPage` Object

feat(profiles): include additional fields in profile settings

---

packages/profiles/source/environment.test.ts
packages/profiles/source/profile.enum.contract.ts
packages/profiles/source/profile.test.ts
packages/profiles/source/profile.validator.test.ts
packages/profiles/source/profile.validator.ts

With https://github.com/ArdentHQ/arkconnect-extension/pull/131 we don't need to store `hasOnboarded` in profile.settings()
Task https://app.clickup.com/t/86drujzwe

refactor: remove unused `hasOnboarded` profile setting

---

packages/profiles/source/environment.test.ts
packages/profiles/source/profile.test.ts
packages/profiles/source/profile.validator.test.ts

A minor adjustment in tests to use `path` instead of `name` for `lastVisitedPage` input data. 
See conversation https://github.com/ArdentHQ/arkconnect-extension/pull/143#pullrequestreview-1931087595

test: adjust `lastVisitedPage` input data

---

packages/ledger/package.json
packages/ledger/source/index.ts
pnpm-lock.yaml

`@ledgerhq/hw-transport-u2f` is officially deprecated and `webusb` or `webhid` are the recommended web-based transports for browsers that support these APIs (currently chromium based browsers).
See more: https://www.npmjs.com/package/@ledgerhq/hw-transport-u2f

refactor: remove deprecated ledger `u2f` transport

---

packages/mainsail/source/transaction.service.ts
packages/mainsail/webpack.config.cjs

Extends mainsail webpack.config from base, and removes duplicate config definitions.

refactor: extend mainsail webpack config from base

---

packages/mainsail/source/fee.service.ts

Removes static fees mock and fetches them from network. 
Part of https://app.clickup.com/t/86dt23t38

refactor: remove static fees mock

---

packages/mainsail/source/confirmed-transaction.dto.ts

https://app.clickup.com/t/86dt1r0pt
this only  handles the confirmation and timestamp mocks. For sender we need a network to derive the proper address from a public key if we have to go down that route

fix: remove mocked timestamp and confirmation fields

---

packages/profiles/source/delegate.service.ts

- Error message has been updated in `findDelegateByAttribute` method.

refactor: update delegate search error message

---

packages/ark/source/index.ts

Usage:
```tsx
import { ARK, NetworkManager } from '@ardenthq/sdk-ark`
const networkConfigs = new NetworkManager()
networkConfigs.all()
```

refactor(ark): expose `NetworkManager`

---

packages/mainsail/source/index.ts

Exposes the NetworkManager instance in the sdk-mainsail package to allow consumers to access network configurations (milestones,  manifest).
Usage:
```tsx
import { NetworkManager } from '@ardenthq/sdk-mainsail`
const networkConfigs = new NetworkManager()
networkConfigs.all()
```

refactor(mainsail): expose `NetworkManager`

---

packages/profiles/source/transaction-index.ts

https://app.clickup.com/t/86dtjpcuz
The condition used to only apply to transactions that return `true` for `isSent` or `isConfirmed`. During my test, all transactions in my wallet returned false for both, which kept all my wallets as "cold." This was incorrect.
From my understanding, a wallet should be considered hot once it has any transaction, but it’s better to double-check.

fix: wallet cold/hot status issue

---

packages/profiles/source/wallet.factory.contract.ts
packages/profiles/source/wallet.factory.ts

Closes: https://app.clickup.com/t/86dtr0w28
For testing:
- execute - `pnpm sdk:install-local ../platform-sdk/`
- replace this line in arkvault: https://github.com/ArdentHQ/arkvault/blob/693ed0a505b69069525a3011bf1270b77aedc790/src/app/hooks/use-fees.ts#L59
```
const getWallet = useCallback(
async (coin: string, network: string) => profile.walletFactory().generate({ coin, network, withPublicKey: true }),
[profile],
);
```
- try to make a musig tx with ARK network - you should have `fee` input populated

refactor: add public key generation

---

packages/ark/source/client.service.ts
packages/sdk/source/client.contract.ts

Closes https://app.clickup.com/t/86dv0zdna
Adds a new `types` property in client transaction query https://github.com/ArdentHQ/platform-sdk/blob/c16c6988675766178d5a6c3231dae981b00ea523/packages/sdk/source/client.contract.ts#L75 to allow querying by  multiple transaction types.
When multiple types are added it transforms to `&type=2,3,4` format in query search params. 
Example format (for delegate registration &  multisignature):
```
https://ark-test.arkvault.io/api/transactions?limit=30&address=D6wMj3ZU1qVLzc1QGJ6VDfWK1ThuP8qJfH&type=2%2C4&typeGroup=1
```

feat(ark): add support for multiple types in transactions query

---

packages/ark/source/client.service.ts
packages/helpers/package.json

Related to https://app.clickup.com/t/86dunurq3
Fixes an issue where the typegroup is wrong when the filters have both core & magistrate transaction types.

fix(ark): use correct type group on core & magistrate tx type filters

---

packages/ark/source/client.service.ts

Additional fixes for https://app.clickup.com/t/86dunurq3
Can be tested in https://github.com/ArdentHQ/arkvault/pull/798

fix: correct filtering for transfer transactions

---

docs/profiles/wallets.md
packages/mainsail/source/transaction.service.test.ts
packages/mainsail/source/transaction.service.ts
packages/profiles/source/wallet-transaction.service.contract.ts
packages/profiles/source/wallet-transaction.service.ts
packages/sdk/source/transaction.contract.ts
packages/sdk/source/transaction.service.ts

Please review companion PR first: #124 
Continuation of: https://app.clickup.com/t/86dv1qa8g - resignation part
**Changelog:**
- implements validator resignation for Mainsail network by using EVM call
- deprecates existing `delegateResignation` method
- adds unit tests for the validator resignation
**In action:**
[Screencast from 2024-11-29 17-24-03.webm](https://github.com/user-attachments/assets/de71b784-19b2-45be-b472-7a8c26f23d9f)

feat: implement EVM validator resignation transaction

---

packages/mainsail/source/transaction-type.service.ts

Closes: https://app.clickup.com/t/86dv9xhhq
This PR refactors `isTransfer` method to use an empty string to decide if a transaction is a transfer

refactor: use empty string to identify transfer transactions

---

packages/sdk/source/signed-transaction.dto.ts

Closes: https://app.clickup.com/t/86dvcw560
I wanted to make `#types` in `ConfirmedTransactionData` and `SignedTransactionData` classes to be the same, however, there are some methods that are not implemented for the later, and it causes errors in some cases, that is why reverting the change.
https://github.com/ArdentHQ/platform-sdk/pull/134/files#diff-4013e06f07c9ccf0aa530bfb94a56d6bc1d3acce819b7342fec9b95a3d5dc14cR25

fix: remove unsupported types for signed transaction class

---

packages/mainsail/source/confirmed-transaction.dto.ts
packages/mainsail/source/helpers/format-units.test.ts
packages/mainsail/source/helpers/format-units.ts
packages/mainsail/source/helpers/parse-units.test.ts
packages/mainsail/source/helpers/parse-units.ts
packages/mainsail/source/signed-transaction.dto.ts
packages/mainsail/source/transaction.service.test.ts
packages/mainsail/source/transaction.service.ts
packages/mainsail/source/transaction.service.votes.test.ts

- The following helpers: `formatUnits` and `parseUnits`, have been refactored to return the `BigNumber` instead of a string or a number.
- Implementations of these methods have been refactored.
- Unit tests have also been refactored to support this change.

refactor: adjust helpers return type

---

packages/mainsail/source/fee.service.ts
packages/mainsail/source/transaction.service.test.ts
packages/mainsail/source/transaction.service.ts
packages/mainsail/source/transaction.service.votes.test.ts
packages/sdk/source/transaction.contract.ts

As a part of https://app.clickup.com/t/86dvn14ac
Companion PR: https://github.com/ArdentHQ/arkvault/pull/884
This PR refactors logic to use `gasLimit` and `gasPrice` values when sending transfer transactions. 
Note: I had to duplicate some parts as the remaining transaction types are still using old `fee` property.

refactor: use `gasPrice` and `gasLimit` for transactions

---

packages/profiles/source/contact-address.contract.ts
packages/profiles/source/contact-address.repository.contract.ts
packages/profiles/source/contact-address.repository.test.ts
packages/profiles/source/contact-address.repository.ts
packages/profiles/source/contact-address.test.ts
packages/profiles/source/contact-address.ts
packages/profiles/source/contact.repository.contract.ts
packages/profiles/source/contact.repository.test.ts
packages/profiles/source/contact.repository.ts
packages/profiles/source/contact.test.ts
packages/profiles/source/contact.ts

- `Network` has been removed from `Contact` as a required property.
- Methods related to searching contacts by the network and other related methods have also been refactored to support this change.
- Unit tests have been refactored to remove the use of network in them.

refactor: remove network from contact repository

---

packages/ark/source/signed-transaction.dto.ts
packages/mainsail/source/confirmed-transaction.dto.ts
packages/mainsail/source/helpers/decode-function-data.ts
packages/mainsail/source/signed-transaction.dto.ts
packages/mainsail/source/transaction-type.service.test.ts
packages/mainsail/source/transaction-type.service.ts
packages/profiles/source/signed-transaction.dto.ts
packages/profiles/source/transaction.dto.ts
packages/sdk/source/confirmed-transaction.dto.contract.ts
packages/sdk/source/signed-transaction.dto.contract.ts
packages/sdk/source/signed-transaction.dto.ts

Closes: https://app.clickup.com/t/86dvz97hc
**Changelog:**
- updates logic for `Signed` and `Confirmed` transactions to have right `recipients`, `payment` and `amount` data 
- adds `payments()` method for `Signed` transaction class to ensure consistency
- refactors  `decode-function-data.ts` to support multiple `abi`s
- other minor tweaks and fixes
Note: I couldn't test it with the signed transactions, but it works fine with confirmed transactions

refactor: handle multipayment transactions

---

packages/mainsail/source/address.service.test.ts
packages/mainsail/source/confirmed-transaction.dto.test.ts
packages/mainsail/source/public-key.service.test.ts
packages/mainsail/source/transaction-type.service.test.ts
packages/mainsail/source/wallet.dto.test.ts
packages/mainsail/test/fixtures/identity.ts

# [[test] remove multisignature and second signature related tests](https://app.clickup.com/t/86dw1338f)
- All multisignature-related tests that were commented out have been removed from the `mainsail` package.
- Only the tests about falsy assertions related to multisignature or second signature are left in the code since these are valid.
- `identity.ts` file for `mainsail` has also been updated removing all the information related to these kind of transactions.

refactor: remove multisignature related tests

---

packages/mainsail/package.json

- Script for test coverage has been refactored and now will print the correct uncovered files
> Note: I wanted to test setting up minimum percentages for test coverage, but c8 only throws the uncovered files every time I want to do this. Seems like we first need to finish covering all the files before doing this.

refactor: update test coverage script

---

packages/mainsail/.nycrc

- Depends on https://github.com/ArdentHQ/platform-sdk/pull/172
- `index.ts`, `multi-signature-contract`, `ledger.service.types.d.ts`, and all the `distribution` files have been excluded from coverage.

refactor: exclude source and types from coverage

---

packages/profiles/source/serialiser.test.ts
packages/profiles/source/wallet-transaction.service.test.ts
packages/profiles/source/wallet.factory.test.ts
packages/profiles/source/wallet.factory.ts
packages/profiles/source/wallet.mutator.ts
packages/profiles/source/wallet.repository.test.ts
packages/profiles/source/wallet.synchroniser.test.ts
packages/profiles/source/wallet.test.ts
packages/profiles/test/integration/musig.test.helpers.ts
packages/profiles/test/mocking.ts

Currently when a wallet is imported it forces wallet to sync with the network which seems unecessary as the wallet.synchroniser() is already exposed and can be invoked by the caller when needed.
Fixes the issue mentioned in https://github.com/ArdentHQ/arkvault/pull/1011#pullrequestreview-2654556648

refactor: prevent forcing network sync on wallet creation 

---

packages/mainsail/source/ledger.service.ts
packages/mainsail/source/ledger.service.types.ts
packages/mainsail/source/networks/mainsail.devnet.ts
packages/sdk/source/ledger.contract.ts
packages/sdk/source/ledger.service.ts

Part of https://app.clickup.com/t/86dw69x5e
When building the Mainsail package with webpack and @ledgerhq/hw-app-eth, the bundle size becomes very large, leading to deployment failures in arkvault. 
This PR refactors the ledger service to accept a `setupLedgerFactory` from the caller. This change enables arkvault to optionally include `@ledgerhq/hw-app-eth` dependency while still allowing the ledger service to maintain alignment with the existing sdk architecture.
Alternative solutions such as migrating the sdk coin packages into arkvault (see [#1037](https://github.com/ArdentHQ/arkvault/pull/1037)) were attempted as PoC, but they are too costly and introduce risks at multiple levels.

refactor: accept transport instance as a parameter in ledger service

---

packages/ark/source/ledger.service.ts
packages/mainsail/source/ledger.service.ts
packages/sdk/source/ledger.contract.ts

* Expose `pageSize` prop on ledger scan method
* Improve performance on public key reading
* Retry public key fetch on "device busy" error
Additional fixes for https://app.clickup.com/t/86dw8fv7z
Required by https://github.com/ArdentHQ/arkvault/pull/1100

refactor: improve ledger public key reading 

---

packages/mainsail/source/networks/mainsail.mainnet.ts
packages/profiles/source/wallet.service.ts

As a part of: https://app.clickup.com/t/86dwfh8f6
This PR adjusts `syncByProfile` call to ensure that it syncs wallets for the given networks when defined.

refactor: sync profile wallets for given network

---

packages/mainsail/source/wallet.dto.ts

As a part of: https://app.clickup.com/t/86dw69rr1
This PR adds a `isSecondSignature` for `Mainsail` network. For more info please see: https://helloardent.slack.com/archives/C07QTEQJK5K/p1744156811607099?thread_ts=1744123692.471109&cid=C07QTEQJK5K

refactor: add 2nd signature method for Mainsail
